services:
  - type: web
    name: ngo-tracker
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn ngo_tracker.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4