# Generated by Django 5.2.7 on 2025-10-15 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
